### ISSUE TITLE
 Icon DW2PDF Plugin

### ISSUE THREAD

**Issue by CAXAline** [ipari/dokuwiki-template-white#1]
Thank you for a great template.
Eat a problem with a plug-save articles in PDF (https://www.dokuwiki.org/plugin:dw2pdf)
Plugin icon is not displayed correctly.

**Comment by Samhamsam** [comment]
I have the same issue.

**Comment by ipari** [comment]
@CAXAline @Samhamsam I fixed it and released a new version. Thanks for report.

**Comment by CAXAline** [comment]
Thanks!

**Comment by Samhamsam** [comment]
Thank you!

**Comment by CAXAline** [comment]
Hello.
Again, the problem with the plugin icon.
This time it's: https://www.dokuwiki.org/plugin:move
Here is a screenshot: https://yadi.sk/i/Oxeq_oS63GpEvS

**Comment by ipari** [comment]
Have you updated to latest release?

**Comment by CAXAline** [comment]
Yes

**Comment by ipari** [comment]
What caused this issue was that an action button of a move plugin doesn't have an `action` class. I fixed it and shows well.
![image](https://cloud.githubusercontent.com/assets/3617005/24865784/41efff48-1e43-11e7-803a-e797cd72f9b6.png)

**Comment by CAXAline** [comment]
Icons have fallen into place, everything is fine!
But the signature did not appear (
https://yadi.sk/i/hfBWYqN63Gq4TC

**Comment by CAXAline** [comment]
Understood. The inscriptions did not fit. Increased the width of the panel.

**Comment by ipari** [comment]
Modified that issue.
Considering all cases is impossible and your issues makes this template better.
Thank you.
