### ISSUE TITLE
Numbered Headings not display correctly with Chrome 65/66.

### ISSUE THREAD

**Issue by CodingHare** [ipari/dokuwiki-template-white#11]
Hello,
I just found the Numbered Headings function doesn't work properly under Chrome 65&66. Looks like it's heading numbers start to count after the TOC. For example, If the last number of TOC is "6". then the first title will be numbered start from "7". The lower version Chrome (under 65) & Edges & safari & firefox work fine. Would you please take a look at this problem? Thanks!

For more details pls check the attachment.
![issue](https://user-images.githubusercontent.com/20118311/39399938-2b42b280-4ae4-11e8-906c-f23b001f5ec7.JPG)

Best,
Gu

**Comment by ipari** [comment]
I'm watching it. :D

**Comment by CodingHare** [comment]
Hello ipari,
I just solved this problem by adding an addtional counting variable for header. Now the _TOC li_ and the _Header_ are counting on the different track, and it works for me. However I am not sure whether its a good way to solve it, because it cause the code duplication. Looking forward to your Fix. 

Thanks!
Gu

**Comment by ipari** [comment]
Hi, sorry for the late reply. I was too busy for a month.
I fixed this issue and released it. Would you check it?

**Comment by CodingHare** [comment]
Tested and works great for me. Thank you!
