### ISSUE TITLE
2018 releases contain old date 2017-03-11 in template.info.txt

### ISSUE THREAD

**Issue by raabf** [ipari/dokuwiki-template-white#12]
The variable date `date` in `template.info.txt` still contains an old date from the 2017-03-11 release.

https://github.com/ipari/dokuwiki-template-white/blob/5af8cce0b3df97e45346f4fb3c6c8201321cff4b/template.info.txt#L4

This holds for both 2018-* releases. As a result, the dokuwiki updater reports that the 2017-03-11 version is  installed and prompts for an update to the 2018-05-20, but in an endless loop.

**Comment by ipari** [comment]
Thanks for your report.
Modifying that file is too easy to forgot ;-(

**Comment by raabf** [comment]
:+1:  tanks for fixing, works now
