### ISSUE TITLE
French localisation

### ISSUE THREAD

**Issue by 7163D** [ipari/dokuwiki-template-white#14]
Hi!
I've translated the theme to french:

Lang.php :

$lang['existing'] = 'La couleur des liens vers une page existante';
$lang['missing'] = 'La couleur des liens vers une page qui n'existe pas';
$lang['numbered_heading'] = 'La couleur pour les numéros d'en-tête';
$lang['font_size'] = 'La taille globale de police (%, px, pt)';
$lang['line_height'] = 'L'épaisseur globale des lines (x.x, %)';
$lang['body_width'] = 'La largeur du corps(%, px, em, ...)';
$lang['sidebar_width'] = 'La taille de la barre latérale, si elle existe(%, px, em, ...)';//

settings.php:
$lang['numberedHeading'] = 'Nombre de titres';
$lang['tocPosition'] = 'Position de la table des matières';
$lang['tocPosition_o_dokuwiki'] = 'DokuWiki';
$lang['tocPosition_o_wikipedia'] = 'Wikipedia';
$lang['footer'] = 'Pied de page, laisser vide pour désactiver le pied de page.';

Thanks for you works ;)

**Comment by 7163D** [comment]
Hi!
I've translated the theme to french:

Lang.php :
<?php

// style.ini values

$lang['existing'] = 'La couleur des liens vers une page existante';
$lang['missing'] = 'La couleur des liens vers une page qui n'existe pas';
$lang['numbered_heading'] = 'La couleur pour les numéros d'en-tête';
$lang['font_size'] = 'La taille globale de police (%, px, pt)';
$lang['line_height'] = 'L'épaisseur globale des lines (x.x, %)';
$lang['body_width'] = 'La largeur du corps(%, px, em, ...)';
$lang['sidebar_width'] = 'La taille de la barre latérale, si elle existe(%, px, em, ...)';//

settings.php:
`<?php

$lang['numberedHeading'] = 'Nombre de titres';
$lang['tocPosition'] = 'Position de la table des matiÃ¨res';
$lang['tocPosition_o_dokuwiki'] = 'DokuWiki';
$lang['tocPosition_o_wikipedia'] = 'Wikipedia';
$lang['footer'] = 'Pied de page, laisser vide pour désactiver le pied de page.';`

Thanks for you works ;)

**Comment by ipari** [comment]
Released a new version with your work.  
Thank for your contribution!
