### ISSUE TITLE
logos

### ISSUE THREAD

**Issue by antitoxine** [ipari/dokuwiki-template-white#16]
![logos](https://user-images.githubusercontent.com/64896914/82344455-5b3cc280-99f4-11ea-9a93-09aab6c2a06f.png)
I would like to have logos like this
thank you
https://ponge.biz/doku/doku.php?id=a:acacia

**Comment by antitoxine** [comment]
i named it white-plus
https://www.ponge.biz/doku/

**Comment by ipari** [comment]
I removed that area to match the design style maybe. Your work is nice  👍
