### ISSUE TITLE
Access key 'f' for Search doesn't work when search field is hidden

### ISSUE THREAD

**Issue by may** [ipari/dokuwiki-template-white#2]
Steps to reproduce:
1. Install white theme.
2. Navigate to a normal wiki page. 
3. Press the correct [access key](https://www.dokuwiki.org/accesskeys) for your platform (eg. Alt-Shift-F for Chrome on Windows) and notice that the focus does not move to the search box.
4. Click on the magnifying glass in the upper right corner, to show the search box.
5. Press the correct access key  again, notice that the focus now moves to the search field because it is visible. 

Is there a way to either fix the accesskey or edit the template's code so that the search field is always visible so the accesskey works again?

Love the theme!

**Comment by ipari** [comment]
I fixed it and released new version.
Thanks for report, @may.

**Comment by may** [comment]
Fixed and works great! Thank you, @ipari!

**Comment by may** [comment]
So, I spoke too soon. It works great, except that it also triggers when you press <Shift>-F, without any other characters -- at least on Windows 10, using Chrome.

Edit: reproduced on Windows 10 using Internet Explorer as well. 

If I'm reading the website correctly it should only trigger when Alt-F or Alt-Shift-F is pressed, at least for Chrome on Windows: https://www.dokuwiki.org/accesskeys

**Comment by ipari** [comment]
Found this problem yesterday too, fixed and released new version.
The problem was that key events for showing search input had intercepted shift key input.
Sorry for trouble, @may.

**Comment by may** [comment]
It works really well; thank you again for the fast turnaround. I use this template daily and it's awesome.

Sidenote, @ipari you might want to bump the 'last updated on' date on the DokuWiki page, so people can see how active you are in developing this: https://www.dokuwiki.org/template:white
:-)

Additionally, FYI, this message appeared when I went to update the theme via the Extension Manager -- not an issue, just a FYI for you in future:

![image](https://cloud.githubusercontent.com/assets/82888/13704654/923e8438-e762-11e5-8a51-73dc66144716.png)

**Comment by ipari** [comment]
Thank you for your detailed feedback! :smile: 
Any feedback and suggestions are welcome.
