### ISSUE TITLE
How does it work automatic numbering for headings 

### ISSUE THREAD

**Issue by CAXAline** [ipari/dokuwiki-template-white#3]
Answer please:  нow does it work "automatic numbering for headings"?

**Comment by ipari** [comment]
You can turn it on in the configuration.
![image](https://cloud.githubusercontent.com/assets/3617005/13802005/d1b0454a-eb7a-11e5-81e3-9a6d199661c0.png)

**Comment by CAXAline** [comment]
@ipari ok, thank you
