### ISSUE TITLE
Fonts cause "\" to display as Korean currency sign on Windows.

### ISSUE THREAD

**Issue by jeroendonkers** [ipari/dokuwiki-template-white#7]
I like the template very much. We use it in our wikis at the department of educational development at Maastricht University in the Netherlands.

The fonts you apply in the styes cause the "\\" character to display as a strikethrough W (the Korean currency sign).

**Comment by ipari** [comment]
I need some clues. Can you give me some information such as your OS, language of OS?

**Comment by jeroendonkers** [comment]
I tested it on Windows 7, US version. I solved the problem by replacing the first two fonts in base,less.  

I can refer to Wikipedia where this problem is also mentioned: https://en.wikipedia.org/wiki/Won_sign

**Comment by ipari** [comment]
That's nice. I'll modify that fonts soon :D

**Comment by ipari** [comment]
Fixed this issue on 7ecd2b454a55733708cd8d08ef535eda2f04dd89
